-- +goose Up
ALTER TABLE metrics ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE metrics DROP COLUMN hash;
ALTER TABLE metrics DROP COLUMN created_at;

-- +goose Down
ALTER TABLE metrics ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE metrics ADD COLUMN hash VARCHAR(255);
ALTER TABLE metrics DROP COLUMN updated_at;
