package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const fileHeader = "// Code generated by cmd/reset; DO NOT EDIT.\n\n"

func generate(targets []targetStruct) error {
	marked := markedSet(targets)

	byPkg := map[*packages.Package][]targetStruct{}
	var order []*packages.Package
	for _, t := range targets {
		if _, ok := byPkg[t.pkg]; !ok {
			order = append(order, t.pkg)
		}
		byPkg[t.pkg] = append(byPkg[t.pkg], t)
	}

	for _, p := range order {
		if err := writePackageFile(p, byPkg[p], marked); err != nil {
			return fmt.Errorf("package %s: %w", p.PkgPath, err)
		}
	}
	return nil
}

// markedSet возвращает множество именованных типов, для которых будет
// сгенерирован Reset(). Используется, чтобы корректно ссылаться на
// вложенные структуры на первом запуске (когда reset.gen.go ещё нет).
func markedSet(targets []targetStruct) map[*types.TypeName]bool {
	out := make(map[*types.TypeName]bool, len(targets))
	for _, t := range targets {
		obj, ok := t.pkg.TypesInfo.Defs[t.typeSpec.Name].(*types.TypeName)
		if !ok {
			continue
		}
		out[obj] = true
	}
	return out
}

func writePackageFile(p *packages.Package, targets []targetStruct, marked map[*types.TypeName]bool) error {
	var buf bytes.Buffer
	buf.WriteString(fileHeader)
	buf.WriteString("package " + p.Name + "\n\n")

	for _, t := range targets {
		method, err := generateMethod(p, t, marked)
		if err != nil {
			return fmt.Errorf("%s: %w", t.typeSpec.Name.Name, err)
		}
		buf.WriteString(method)
		buf.WriteString("\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, buf.String())
		return fmt.Errorf("format: %w", err)
	}

	if len(p.GoFiles) == 0 {
		return fmt.Errorf("no Go files in package")
	}
	outPath := filepath.Join(filepath.Dir(p.GoFiles[0]), "reset.gen.go")
	return os.WriteFile(outPath, src, 0o644)
}

func generateMethod(p *packages.Package, t targetStruct, marked map[*types.TypeName]bool) (string, error) {
	obj := p.TypesInfo.Defs[t.typeSpec.Name]
	if obj == nil {
		return "", fmt.Errorf("no type info")
	}
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return "", fmt.Errorf("not a named type")
	}
	st, ok := named.Underlying().(*types.Struct)
	if !ok {
		return "", fmt.Errorf("not a struct")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "func (r *%s) Reset() {\n", t.typeSpec.Name.Name)
	b.WriteString("\tif r == nil {\n\t\treturn\n\t}\n")

	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		stmt, ok := resetStmt("r."+f.Name(), f.Type(), marked)
		if !ok {
			fmt.Fprintf(os.Stderr, "warning: %s.%s: field %s of type %s — no rule, skipping\n",
				p.PkgPath, t.typeSpec.Name.Name, f.Name(), f.Type())
			continue
		}
		b.WriteString(stmt)
	}

	b.WriteString("}\n")
	return b.String(), nil
}

// resetStmt возвращает statement(ы) для сброса одного поля.
func resetStmt(ref string, t types.Type, marked map[*types.TypeName]bool) (string, bool) {
	if ptr, ok := t.Underlying().(*types.Pointer); ok {
		return pointerStmt(ref, t, ptr.Elem(), marked)
	}
	if hasResetMethod(t, marked) {
		return fmt.Sprintf("\t%s.Reset()\n", ref), true
	}
	switch ut := t.Underlying().(type) {
	case *types.Basic:
		return fmt.Sprintf("\t%s = %s\n", ref, basicZero(ut)), true
	case *types.Slice:
		return fmt.Sprintf("\t%s = %s[:0]\n", ref, ref), true
	case *types.Map:
		return fmt.Sprintf("\tclear(%s)\n", ref), true
	}
	return "", false
}

func pointerStmt(ref string, ptrType types.Type, elem types.Type, marked map[*types.TypeName]bool) (string, bool) {
	if hasResetMethod(ptrType, marked) {
		return fmt.Sprintf("\tif %s != nil {\n\t\t%s.Reset()\n\t}\n", ref, ref), true
	}
	deref := "*" + ref
	switch ut := elem.Underlying().(type) {
	case *types.Basic:
		return fmt.Sprintf("\tif %s != nil {\n\t\t%s = %s\n\t}\n", ref, deref, basicZero(ut)), true
	case *types.Slice:
		return fmt.Sprintf("\tif %s != nil {\n\t\t%s = (%s)[:0]\n\t}\n", ref, deref, deref), true
	case *types.Map:
		return fmt.Sprintf("\tif %s != nil {\n\t\tclear(%s)\n\t}\n", ref, deref), true
	}
	return "", false
}

func basicZero(b *types.Basic) string {
	switch {
	case b.Info()&types.IsBoolean != 0:
		return "false"
	case b.Info()&types.IsString != 0:
		return `""`
	case b.Info()&types.IsNumeric != 0:
		return "0"
	}
	return ""
}

// hasResetMethod возвращает true, если на типе t (или *t) определён
// метод Reset() без параметров и без возвращаемых значений, либо тип
// помечен // generate:reset (т.е. метод будет сгенерирован).
func hasResetMethod(t types.Type, marked map[*types.TypeName]bool) bool {
	check := t
	if p, ok := t.(*types.Pointer); ok {
		check = p.Elem()
	}
	if named, ok := check.(*types.Named); ok {
		if marked[named.Obj()] {
			return true
		}
	}
	obj, _, _ := types.LookupFieldOrMethod(t, true, nil, "Reset")
	if obj == nil {
		return false
	}
	fn, ok := obj.(*types.Func)
	if !ok {
		return false
	}
	sig, ok := fn.Type().(*types.Signature)
	if !ok {
		return false
	}
	return sig.Params().Len() == 0 && sig.Results().Len() == 0
}

func isGenerated(f *ast.File) bool {
	for _, cg := range f.Comments {
		// заголовок DO NOT EDIT должен находиться до package-объявления
		if cg.Pos() >= f.Package {
			break
		}
		for _, c := range cg.List {
			if generatedRe.MatchString(c.Text) {
				return true
			}
		}
	}
	return false
}
