// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/agent.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/iliaonishchenko/aggreg8/internal/model"
)

// MockCollectorService is a mock of CollectorService interface.
type MockCollectorService struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorServiceMockRecorder
}

// MockCollectorServiceMockRecorder is the mock recorder for MockCollectorService.
type MockCollectorServiceMockRecorder struct {
	mock *MockCollectorService
}

// NewMockCollectorService creates a new mock instance.
func NewMockCollectorService(ctrl *gomock.Controller) *MockCollectorService {
	mock := &MockCollectorService{ctrl: ctrl}
	mock.recorder = &MockCollectorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectorService) EXPECT() *MockCollectorServiceMockRecorder {
	return m.recorder
}

// CollectRuntime mocks base method.
func (m *MockCollectorService) CollectRuntime() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CollectRuntime")
}

// CollectRuntime indicates an expected call of CollectRuntime.
func (mr *MockCollectorServiceMockRecorder) CollectRuntime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectRuntime", reflect.TypeOf((*MockCollectorService)(nil).CollectRuntime))
}

// CollectSystem mocks base method.
func (m *MockCollectorService) CollectSystem() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CollectSystem")
}

// CollectSystem indicates an expected call of CollectSystem.
func (mr *MockCollectorServiceMockRecorder) CollectSystem() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectSystem", reflect.TypeOf((*MockCollectorService)(nil).CollectSystem))
}

// GetMetrics mocks base method.
func (m *MockCollectorService) GetMetrics() [][]*models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].([][]*models.Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockCollectorServiceMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockCollectorService)(nil).GetMetrics))
}

// MockSenderService is a mock of SenderService interface.
type MockSenderService struct {
	ctrl     *gomock.Controller
	recorder *MockSenderServiceMockRecorder
}

// MockSenderServiceMockRecorder is the mock recorder for MockSenderService.
type MockSenderServiceMockRecorder struct {
	mock *MockSenderService
}

// NewMockSenderService creates a new mock instance.
func NewMockSenderService(ctrl *gomock.Controller) *MockSenderService {
	mock := &MockSenderService{ctrl: ctrl}
	mock.recorder = &MockSenderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSenderService) EXPECT() *MockSenderServiceMockRecorder {
	return m.recorder
}

// SendJSONWithRetries mocks base method.
func (m *MockSenderService) SendJSONWithRetries(metrics ...*models.Metrics) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range metrics {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendJSONWithRetries", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendJSONWithRetries indicates an expected call of SendJSONWithRetries.
func (mr *MockSenderServiceMockRecorder) SendJSONWithRetries(metrics ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendJSONWithRetries", reflect.TypeOf((*MockSenderService)(nil).SendJSONWithRetries), metrics...)
}
